<?php

$locations = array(
  "https://www.mediapart.fr/journal/france/141221/affaire-des-contrats-russes-alexandre-benalla-place-en-garde-vue",
  "https://www.mediapart.fr/journal/france/141221/greve-dans-la-justice-les-causes-d-une-mobilisation-inedite",
  "https://www.mediapart.fr/journal/france/121221/nouvelle-caledonie-macron-se-felicite-de-resultats-qui-ne-veulent-rien-dire",
  "https://www.mediapart.fr/journal/international/091221/macron-met-deja-l-europe-son-service",
  "https://www.mediapart.fr/journal/france/200319/nouvelles-mises-en-examen-pour-alexandre-benalla",
  "https://www.mediapart.fr/journal/economie/040219/affaire-benalla-perquisition-avortee-mediapart",
  "https://www.mediapart.fr/journal/france/190219/alexandre-benalla-place-en-detention-provisoire",
  "https://www.mediapart.fr/journal/france/081221/condamne-par-la-justice-le-ministre-alain-griset-quitte-le-gouvernement",
  "https://www.mediapart.fr/journal/france/231121/alexis-kohler-un-secretaire-general-de-l-elysee-cerne-par-deux-affaires",
  "https://www.mediapart.fr/journal/economie/231121/la-note-qui-relance-l-affaire-kohler",
  "https://www.mediapart.fr/journal/france/dossier/notre-dossier-l-affaire-macron-benalla",
  "https://www.mediapart.fr/journal/dossier/france/le-proces-benalla-l-ombre-de-macron",
  "https://www.mediapart.fr/journal/france/191218/les-rebondissements-de-l-affaire-benalla",
  "https://www.mediapart.fr/journal/france/110219/les-millions-russes-d-alexandre-benalla",
  "https://www.mediapart.fr/journal/france/120719/nouvelle-plainte-danticor-contre-alexandre-benalla",
  "https://www.mediapart.fr/journal/france/240718/affaire-benalla-l-elysee-joue-la-confrontation",
  "https://www.mediapart.fr/journal/france/190718/l-affaire-benalla-seme-la-panique-l-elysee",
  "https://www.mediapart.fr/journal/france/251218/l-elysee-embarrasse-par-les-voyages-d-affaires-de-benalla",
  "https://www.mediapart.fr/journal/france/300418/campagne-macron-les-preuves-du-mensonge",
  "https://www.mediapart.fr/journal/economie/040715/aeroport-de-toulouse-le-deuxieme-mensonge-de-macron",
  "https://www.mediapart.fr/journal/france/170418/sur-la-zad-les-mensonges-d-emmanuel-macron",
  "https://www.mediapart.fr/journal/france/310521/bure-un-proces-politiquement-radioactif",
  "https://www.mediapart.fr/journal/france/081018/bure-nouveau-coup-de-pression-contre-les-opposant-e-s",
  "https://www.mediapart.fr/journal/france/dossier/notre-dossier-gerard-collomb-ministre-ephemere",
  "https://www.mediapart.fr/journal/france/021018/gerard-collomb-le-mentor-decu",
  "https://www.mediapart.fr/journal/france/021018/collomb-redemande-macron-daccepter-sa-demission",
  "https://www.mediapart.fr/journal/france/180918/collomb-lance-les-quartiers-de-reconquete-republicaine",
  "https://www.mediapart.fr/journal/france/210617/reserve-parlementaire-le-systeme-gerard-collomb",
  "https://www.mediapart.fr/journal/france/110917/l-etat-d-urgence-permanent-arrive-l-assemblee",
  "https://www.mediapart.fr/journal/france/011117/la-france-bascule-dans-letat-durgence-permanent",
  "https://www.mediapart.fr/journal/france/250917/etat-durgence-permanent-en-examen-lassemblee-linquietude-grandit",
  "https://www.mediapart.fr/journal/fil-dactualites/230921/responsabilite-penale-drones-policiers-l-assemblee-adopte-le-projet-de-loi",
  "https://www.mediapart.fr/journal/france/150921/la-frenesie-securitaire-de-la-majorite",
  "https://www.mediapart.fr/journal/france/dossier/loi-securite-globale-notre-dossier",
  "https://www.mediapart.fr/journal/fil-dactualites/200521/policiers-filmes-le-conseil-constitutionnel-censure-l-ex-article-24-controverse",
  "https://www.mediapart.fr/journal/france/200521/securite-globale-le-rappel-du-conseil-constitutionnel-aux-libertes-fondamentales",
  "https://www.mediapart.fr/journal/fil-dactualites/200521/securite-globale-darmanin-proposera-d-ameliorer-les-dispositions-retoquees-par-le-conseil-constit",
  "https://www.mediapart.fr/journal/france/dossier/laffaire-gerald-darmanin",
  "https://www.mediapart.fr/journal/france/170517/gerald-darmanin-un-sarkozyste-devenu-macroniste",
  "https://www.mediapart.fr/journal/fil-dactualites/080720/castex-assume-totalement-la-nomination-de-darmanin"
);

header("Location: " . $locations[rand(0, count($locations)-1)], true, 302);
